### ISSUE TITLE
building image does not work

### ISSUE THREAD

**Issue by SamuelYaron** [blue-build/cli#339]
Hi, I just created a new project with bluebuild.

Unfortunately the image does not build. Here is the error I am getting:

```
$ bluebuild --version
BlueBuild 0.9.3
branch:
commit_hash:
build_time:2025-01-23 12:08:33 +01:00
build_env:rustc 1.84.0 (9fc6b4312 2025-01-07) (Homebrew),

$ bluebuild new hyprtomic
✔ What would you like to name your image? · hyprtomic
✔ What is the registry for the image? (e.g. ghcr.io or registry.gitlab.com) · ghcr.io
✔ What is the name of your org/username? · samuelyaron
✔ Write a short description of your image: · ublue image with hyprland
✔ Are you building on Github or Gitlab? · Github
Private key written to cosign.key
Public key written to cosign.pub
[main (root-commit) 51b2fed] chore: Initial Commit
 11 files changed, 356 insertions(+)
 create mode 100644 .github/dependabot.yml
 create mode 100644 .github/workflows/build.yml
 create mode 100644 .gitignore
 create mode 100644 LICENSE
 create mode 100644 README.md
 create mode 100644 cosign.pub
 create mode 100644 files/scripts/example.sh
 create mode 100644 files/system/etc/.gitkeep
 create mode 100644 files/system/usr/.gitkeep
 create mode 100644 modules/.gitkeep
 create mode 100644 recipes/recipe.yml
INFO  => Created new BlueBuild project in hyprtomic
$ cd hyprtomic/
$ bluebuild build
INFO  => Recipe ./recipes/recipe.yml is valid
INFO  => Templating for recipe at ./recipes/recipe.yml
INFO  => Retrieving OS version from ghcr.io/ublue-os/silverblue-main:41
ERROR => Failed:

  × invalid reference format
```

**Comment by xynydev** [comment]
Good that you reported this so we have a proper tracking issue. I have experienced this problem as well and briefly mentioned it on the Discord. 

I'm not sure what the cause is, but the way I fixed it is running `bluebuild` with `sudo`. Sometimes changing the inspect driver also helps, check out the flag and usage with `bluebuild build --help`.

**Comment by SamuelYaron** [comment]
> Good that you reported this so we have a proper tracking issue. I have experienced this problem as well and briefly mentioned it on the Discord.
> 
> I'm not sure what the cause is, but the way I fixed it is running `bluebuild` with `sudo`. Sometimes changing the inspect driver also helps, check out the flag and usage with `bluebuild build --help`.

Thanks for the hints. Setting the inspect driver per argument fails with the same error:

<details>
<summary>command output</summary>

```
$ bluebuild build -v -I skopeo
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/module-v1.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/module-v1.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/script.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/module-v1.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/copy.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/stage-v1.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/stage-v1.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/akmods.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/justfiles.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/fonts.json
[19:29:18 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/bling.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/brew.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/signing.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/initramfs.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/signing.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/default-flatpaks.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/chezmoi.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/chezmoi.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/gnome-extensions.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/gschema-overrides.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/files.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/files.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/systemd.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/rpm-ostree.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/yafti.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/rpm-ostree.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/containerfile.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/containerfile.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/containerfile.json
[19:29:19 DEBUG] => Retrieving schema from https://schema.blue-build.org/modules/containerfile.json
[19:29:19 DEBUG] => Validating recipe ./recipes/recipe.yml
[19:29:19 DEBUG] => Validating modules for recipe ./recipes/recipe.yml
[19:29:19  INFO] => Recipe ./recipes/recipe.yml is valid
[19:29:19 DEBUG] => Deserializing recipe
[19:29:19 DEBUG] => Recipe contents: ---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprtomic
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully


[19:29:19  INFO] => Templating for recipe at ./recipes/recipe.yml
[19:29:19  INFO] => Retrieving OS version from ghcr.io/ublue-os/silverblue-main:41
[19:29:21 DEBUG] => Successfully inspected image ghcr.io/ublue-os/silverblue-main:41!
[19:29:21 ERROR] => Failed:

  × invalid reference format
```
</details>

Using sudo did not help either.

One more note of interest might be, that the Github action works fine.

**Comment by xynydev** [comment]
I did some testing of my own. I found that this error never happens with the `bluebuild` version baked into my image at `/usr/bin/bluebuild`, but it happened with the version installed from cargo with the `skopeo` inspect driver and without sudo.

I updated `bluebuild` with `cargo install --locked blue-build`, and tried building with various inspect drivers.

```
❯ bluebuild build -I skopeo
× invalid reference format

❯ bluebuild build -I podman
× invalid reference format

❯ bluebuild build -I docker
× invalid reference format
```

The errors were fixed with `sudo` on my machine earlier, because running with `sudo` does not use `~/.cargo/bin/bluebuild`. If I manually specify the path, I get the errors even with `sudo`. Similarly, if I manually use `/usr/bin/bluebuild` as the user the errors do not happen.

This must be some issue with the cargo distribution, then, I guess.

Here's the related parts from my `TRACE` log. Seems pretty similar to what @SamuelYaron had.

```
[17:45:54 TRACE blue_build_process_management::drivers:196] => Driver::get_os_version(Reference {
    registry: "ghcr.io",
    repository: "ublue-os/silverblue-nvidia",
    tag: Some(
        "latest",
    ),
    digest: None,
})
[17:45:54 INFO  blue_build_process_management::drivers:207] => Retrieving OS version from ghcr.io/ublue-os/silverblue-nvidia:latest
[17:45:54 TRACE blue_build_process_management::drivers::skopeo_driver:30] => SkopeoDriver::get_metadata(GetMetadataOpts {
    image: Reference {
        registry: "ghcr.io",
        repository: "ublue-os/silverblue-nvidia",
        tag: Some(
            "latest",
        ),
        digest: None,
    },
    platform: Native,
})
[17:45:54 TRACE blue_build_process_management::drivers::skopeo_driver:51] => "skopeo" "inspect" "docker://ghcr.io/ublue-os/silverblue-nvidia:latest"
[17:46:22 DEBUG blue_build_process_management::drivers::skopeo_driver:59] => Successfully inspected image ghcr.io/ublue-os/silverblue-nvidia:latest!
[17:46:22 TRACE blue_build_process_management::drivers:227] => os_version: 41
[17:46:22 TRACE blue_build_process_management::drivers:173] => Driver::get_build_id()
[17:46:22 TRACE blue_build_process_management::drivers::local_driver:70] => LocalDriver::get_repo_url()
[17:46:22 ERROR blue_build::commands:38] => Failed:

  × invalid reference format
```

**Comment by gmpinder** [comment]
Found the issue, released a fix 952096c0148f14830e91164a00158d51e8605716

**Comment by proborek** [comment]
Still the same issue (unknown flag --format) both using image or recipe option  with version 0.9.6 installed via cargo. Or is there any cleanup needed after update from 0.9.3?
